export type GlossaryTerm = {
  id: string;
  term: string;
  definition: string;
  detail: string;
  href: string;
  linkLabel: string;
};

export const glossaryTerms: GlossaryTerm[] = [
  { id: "actif", term: "Actif", definition: "Bien ou droit ayant une valeur économique et détenu par une personne ou un foyer.", detail: "Dans un bilan personnel, les liquidités, placements, biens immobiliers et certains biens cessibles peuvent être comptés parmi les actifs, selon une convention de valorisation cohérente.", href: "/calculateur/patrimoine-net", linkLabel: "Calculer son patrimoine net" },
  { id: "amortissement", term: "Amortissement d’un prêt", definition: "Remboursement progressif du capital emprunté au fil des échéances.", detail: "Dans un prêt amortissable, chaque mensualité comprend généralement une part de capital et une part d’intérêts. La répartition évolue avec le capital restant dû.", href: "/guides/calcul-mensualite-pret", linkLabel: "Comprendre une mensualité" },
  { id: "capital", term: "Capital", definition: "Somme placée, détenue ou empruntée servant de base à un calcul financier.", detail: "Selon le contexte, il peut s’agir du capital initial d’une épargne, du capital final projeté ou du capital restant dû sur un crédit.", href: "/calculateur/interets-composes", linkLabel: "Projeter un capital" },
  { id: "capitalisation", term: "Capitalisation", definition: "Mécanisme par lequel les gains s’ajoutent au capital et peuvent produire à leur tour de nouveaux gains.", detail: "L’effet dépend de la durée, du rythme des versements, du rendement net et de la fréquence à laquelle les gains sont réinvestis.", href: "/guides/interets-composes", linkLabel: "Guide des intérêts composés" },
  { id: "epargne-precaution", term: "Épargne de précaution", definition: "Réserve disponible destinée aux dépenses imprévues ou à une baisse temporaire de revenu.", detail: "Elle se distingue de l’épargne prévue pour un projet et d’un investissement de long terme. Sa disponibilité et la préservation du capital priment généralement sur le rendement.", href: "/guides/construire-fonds-urgence", linkLabel: "Construire sa réserve" },
  { id: "inflation", term: "Inflation", definition: "Hausse générale et durable des prix mesurée à partir d’un ensemble de biens et services.", detail: "L’indice des prix à la consommation mesure une moyenne nationale. L’évolution ressentie par un foyer peut différer selon la composition de ses dépenses.", href: "/calculateur/rendement-apres-inflation", linkLabel: "Mesurer l’effet sur l’épargne" },
  { id: "interets-composes", term: "Intérêts composés", definition: "Intérêts calculés sur le capital de départ et sur les intérêts déjà accumulés.", detail: "Une projection à taux constant simplifie la réalité : les rendements peuvent varier et les frais, la fiscalité ou l’inflation réduisent le résultat disponible.", href: "/calculateur/interets-composes", linkLabel: "Calculer les intérêts composés" },
  { id: "passif", term: "Passif", definition: "Dette ou engagement financier venant diminuer la valeur nette d’un patrimoine.", detail: "Pour un bilan personnel, on retient notamment les capitaux restant dus sur les prêts, et non la somme brute de toutes les mensualités futures.", href: "/guides/calculer-patrimoine-net", linkLabel: "Recenser actifs et dettes" },
  { id: "patrimoine-net", term: "Patrimoine net", definition: "Différence entre la valeur totale des actifs détenus et les dettes restant à rembourser.", detail: "Il s’agit d’une photographie à une date donnée. Son évolution peut venir de l’épargne, du remboursement des dettes ou de la variation de valeur des actifs.", href: "/calculateur/patrimoine-net", linkLabel: "Faire le calcul" },
  { id: "rendement-nominal", term: "Rendement nominal", definition: "Progression d’un placement exprimée en euros courants, avant correction de l’inflation.", detail: "Pour comparer utilement des solutions, il faut préciser si le rendement est présenté avant ou après frais et fiscalité.", href: "/guides/rendement-reel-inflation", linkLabel: "Passer au rendement réel" },
  { id: "rendement-reel", term: "Rendement réel", definition: "Rendement d’un placement après prise en compte de l’inflation.", detail: "La formule exacte est (1 + rendement nominal) ÷ (1 + inflation) − 1. Un rendement réel négatif peut coexister avec une hausse du capital en euros.", href: "/calculateur/rendement-apres-inflation", linkLabel: "Calculer le rendement réel" },
  { id: "reste-a-vivre", term: "Reste à vivre", definition: "Montant disponible après déduction des charges retenues dans l’analyse du budget.", detail: "Il complète le taux d’effort : deux foyers présentant le même pourcentage d’endettement peuvent conserver des montants disponibles très différents.", href: "/guides/calcul-taux-endettement", linkLabel: "Taux et reste à vivre" },
  { id: "taeg", term: "TAEG", definition: "Taux annuel effectif global exprimant le coût annuel tout compris d’un crédit selon les éléments réglementairement retenus.", detail: "Il inclut notamment les intérêts et certains frais nécessaires à l’obtention du prêt. Il est plus complet que le seul taux nominal pour comparer des offres.", href: "/guides/calcul-mensualite-pret", linkLabel: "Comparer les coûts d’un prêt" },
  { id: "taux-effort", term: "Taux d’effort", definition: "Rapport entre les charges d’emprunt retenues et les revenus retenus, exprimé en pourcentage.", detail: "Pour le crédit immobilier, le HCSF encadre en principe ce taux à 35 %, assurance comprise, avec une marge de flexibilité pour les établissements prêteurs.", href: "/calculateur/taux-endettement", linkLabel: "Calculer le taux d’effort" },
  { id: "taux-nominal", term: "Taux nominal", definition: "Taux utilisé pour calculer les intérêts d’un prêt ou la rémunération d’un placement, hors certains frais annexes.", detail: "Pour un crédit, il ne suffit pas à comparer le coût complet : l’assurance, les garanties et les frais peuvent modifier le TAEG et le montant total dû.", href: "/calculateur/mensualite-pret", linkLabel: "Simuler une mensualité" },
];
